name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  # Update to v3
      - uses: actions/setup-node@v3  # Update to v3
        with:
          node-version: 20  # Ensure you're using Node.js 20 (or Node.js 16)
      - run: npm ci
      - run: npm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  # Update to v3
      - uses: actions/setup-node@v3  # Update to v3
        with:
          node-version: 20  # Ensure you're using Node.js 20
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}